# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\ui\add_enterprise__batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddBatchDialog(object):
    def setupUi(self, AddBatchDialog):
        AddBatchDialog.setObjectName("AddBatchDialog")
        AddBatchDialog.resize(470, 329)
        self.text_edit_add_batch = QtWidgets.QPlainTextEdit(AddBatchDialog)
        self.text_edit_add_batch.setGeometry(QtCore.QRect(10, 10, 451, 251))
        self.text_edit_add_batch.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.text_edit_add_batch.setObjectName("text_edit_add_batch")
        self.button_add_batch = QtWidgets.QPushButton(AddBatchDialog)
        self.button_add_batch.setGeometry(QtCore.QRect(190, 270, 91, 51))
        self.button_add_batch.setObjectName("button_add_batch")

        self.retranslateUi(AddBatchDialog)
        QtCore.QMetaObject.connectSlotsByName(AddBatchDialog)

    def retranslateUi(self, AddBatchDialog):
        _translate = QtCore.QCoreApplication.translate
        AddBatchDialog.setWindowTitle(_translate("AddBatchDialog", "add_batch_dialog"))
        self.button_add_batch.setText(_translate("AddBatchDialog", "确认导入"))
