# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\ui\AddEnterpriseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 195)
        Dialog.setMinimumSize(QtCore.QSize(400, 195))
        Dialog.setMaximumSize(QtCore.QSize(400, 195))
        self.label_enterprise_name = QtWidgets.QLabel(Dialog)
        self.label_enterprise_name.setGeometry(QtCore.QRect(50, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_enterprise_name.setFont(font)
        self.label_enterprise_name.setObjectName("label_enterprise_name")
        self.lineEdit_enterprise_name = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_enterprise_name.setGeometry(QtCore.QRect(130, 50, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_enterprise_name.setFont(font)
        self.lineEdit_enterprise_name.setText("")
        self.lineEdit_enterprise_name.setObjectName("lineEdit_enterprise_name")
        self.button_add_enterprise = QtWidgets.QPushButton(Dialog)
        self.button_add_enterprise.setGeometry(QtCore.QRect(90, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.button_add_enterprise.setFont(font)
        self.button_add_enterprise.setObjectName("button_add_enterprise")
        self.button_save_and_close = QtWidgets.QPushButton(Dialog)
        self.button_save_and_close.setGeometry(QtCore.QRect(220, 120, 91, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(11)
        self.button_save_and_close.setFont(font)
        self.button_save_and_close.setObjectName("button_save_and_close")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "添加企业"))
        self.label_enterprise_name.setText(_translate("Dialog", "单位名称:"))
        self.button_add_enterprise.setText(_translate("Dialog", "继续添加"))
        self.button_save_and_close.setText(_translate("Dialog", "保存并关闭"))
