# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\ui\add_enterprise__batch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEnterpriseBatchDialog(object):
    def setupUi(self, AddEnterpriseBatchDialog):
        AddEnterpriseBatchDialog.setObjectName("AddEnterpriseBatchDialog")
        AddEnterpriseBatchDialog.resize(470, 329)
        self.text_edit_add_enterprise_batch = QtWidgets.QPlainTextEdit(AddEnterpriseBatchDialog)
        self.text_edit_add_enterprise_batch.setGeometry(QtCore.QRect(10, 10, 451, 251))
        self.text_edit_add_enterprise_batch.setObjectName("text_edit_add_enterprise_batch")
        self.button_add_enterprise_batch = QtWidgets.QPushButton(AddEnterpriseBatchDialog)
        self.button_add_enterprise_batch.setGeometry(QtCore.QRect(190, 270, 91, 51))
        self.button_add_enterprise_batch.setObjectName("button_add_enterprise_batch")

        self.retranslateUi(AddEnterpriseBatchDialog)
        QtCore.QMetaObject.connectSlotsByName(AddEnterpriseBatchDialog)

    def retranslateUi(self, AddEnterpriseBatchDialog):
        _translate = QtCore.QCoreApplication.translate
        AddEnterpriseBatchDialog.setWindowTitle(_translate("AddEnterpriseBatchDialog", "批量导入企业"))
        self.button_add_enterprise_batch.setText(_translate("AddEnterpriseBatchDialog", "确认录入"))
